os: linux
dist: focal
language: generic
addons:
  apt:
    packages:
      - libxml-xpath-perl
services:
  - docker

git:
  depth: false

env:
  global:
    - DOCKER_ORG=zencash
    - IMAGE_NAME=sc-ci-base

script:
  - ci/travis_keep_alive.sh
  - ci/tests.sh

jobs:
  include:
    - name: nightly
      env: IMAGE_TAG='focal_rust-nightly_latest' TESTS='010,015,020,030,035,040'
